import './styles.css';
import { awinProducts } from './awinCatalog';
import { priorityProducts } from './priorityCatalog';
type Product={id:string;title:string;url:string;image:string;category:string;width:number;depth:number;height:number;fallback?:string};
const TAG='quecabeaqui-21';
const products:Product[]=[
['hisense','Hisense HS622E10X - Lavavajillas 60 cm','https://www.amazon.es/dp/B0BWH9T9NL?tag=quecabeaqui-21','https://cdn.tien21.es/estaticos/extras/cache/fotos/productos/00/00/24/90/08/500X500_hs622e10x-1-web.webp','Electrodomésticos',59.8,60,84.5,'https://www.milar.es/estaticos/extras/cache/fotos/productos/00/00/24/90/08/500X500_hs622e10x-1-web.jpg'],
['boschdw','Bosch SMS4EMI06E - Lavavajillas Serie 4','https://www.amazon.es/BOSCH-Lavavajillas-Instalaci%C3%B3n-Inoxidable-SMS4EMI06E/dp/B0CHSCBKMV?tag=quecabeaqui-21','https://m.media-amazon.com/images/I/819yQZcdlCL._AC_SX679_.jpg','Electrodomésticos',60,60,84.5],
['beko45','Beko DIS28023 - Lavavajillas integrado 45 cm','https://www.amazon.es/Beko-lavavajilla-Totalmente-integrado-cubiertos/dp/B08MWQMDGV?tag=quecabeaqui-21','https://m.media-amazon.com/images/I/41VkauQaqvL._AC_SX679_.jpg','Electrodomésticos',45,56,81.8],
['beko481','Beko DIS48120 - Lavavajillas integrable 45 cm','https://www.amazon.es/Lavavajillas-Integrable-BEKO-DIS48120-3%C2%ABBandeja/dp/B0BT866P42?tag=quecabeaqui-21','https://m.media-amazon.com/images/I/61J3JPNXvnL._AC_SY679_.jpg','Electrodomésticos',44.8,55,81.8],
['boschw','Bosch WUU28T63ES - Lavadora Serie 6','https://www.amazon.es/Lavadora-BOSCH-WUU28T63ES-Blanco-1400/dp/B0BR63WK6M?tag=quecabeaqui-21','https://m.media-amazon.com/images/I/71sHOCMggML._AC_SX679_.jpg','Electrodomésticos',59.8,59,84.5],
['hisensew','Hisense WF1I7022BWJ - Lavadora fondo reducido','https://www.amazon.es/Hisense-WF1I7022BWJ-Lavadora-R%C3%A1pidos-Dispensador/dp/B0GT63SB3H?tag=quecabeaqui-21','https://m.media-amazon.com/images/I/71i-EA2mPeL._AC_SX679_.jpg','Electrodomésticos',59.5,43.5,84.5],
['lgw','LG F2X50S8TLB - Lavadora fondo reducido 47,5 cm','https://www.amazon.es/LG-F2X50S8TLB-Inteligente-TurboWash-Programas/dp/B0FZTTN87N?tag=quecabeaqui-21','https://m.media-amazon.com/images/I/61qBqsONQ7L._AC_SX679_.jpg','Electrodomésticos',60,47.5,85],
['tv1','VASAGLE LTV027N01 - Mueble TV 140 cm','https://www.amazon.es/VASAGLE-Ajustables-Televisores-Dormitorio-LTV027N01/dp/B0D2VKWCRX?tag=quecabeaqui-21','https://m.media-amazon.com/images/I/71f64NfjU+L._AC_SX679_.jpg','Muebles',140,40,50],
['tv2','HOMN LIVING Lluvia - Mueble TV 160 cm','https://www.amazon.es/HOMN-LIVING-Mueble-Puertas-Profundo/dp/B0C9QHZFG9?tag=quecabeaqui-21','https://m.media-amazon.com/images/I/31ee98iuGTL._AC_SX679_.jpg','Muebles',160,40,45],
['desk1','Devoko - Escritorio eléctrico 120 x 60 cm','https://www.amazon.es/Devoko-Escritorio-El%C3%A9ctrico-Ajustable-Ensamblado/dp/B09WR9J8YZ?tag=quecabeaqui-21','https://cdn.freshstore.cloud/product/images/21435/625/c/devoko-escritorio-elevable-electrico-120x60-cm-blanco-original.jpg','Escritorios',120,60,122],
['klicelor','Klicelor - Escritorio elevable eléctrico 160 x 60 cm','https://www.amazon.es/dp/B0FJYM52Y2?tag=quecabeaqui-21','https://m.media-amazon.com/images/P/B0FJYM52Y2.01.LZZZZZZZ.jpg','Escritorios',160,60,116,'https://images.weserv.nl/?url=m.media-amazon.com%2Fimages%2FP%2FB0FJYM52Y2.01.LZZZZZZZ.jpg'],
['homall','Homall - Escritorio eléctrico regulable 160 x 70 cm','https://www.amazon.es/Homall-escritorio-el%C3%A9ctrico-regulable-anticolisi%C3%B3n/dp/B0CCNZRC1H?tag=quecabeaqui-21','https://m.media-amazon.com/images/I/61b4CIG-UWL.jpg','Escritorios',160,70,118]
].map(x=>({id:x[0] as string,title:x[1] as string,url:x[2] as string,image:x[3] as string,category:x[4] as string,width:x[5] as number,depth:x[6] as number,height:x[7] as number,fallback:x[8] as string|undefined}));
const awinMapped:Product[]=awinProducts.map(p=>({id:p.id,title:p.title,url:p.url,image:p.image||'https://placehold.co/600x400?text=Qué+Cabe+Aquí',category:p.category,width:p.width,depth:p.depth,height:p.height}));
products.push(...awinMapped);
products.push(...priorityProducts);
const uniqueProducts=[...new Map(products.map(p=>[p.id,p])).values()];
products.splice(0,products.length,...uniqueProducts);
const cats=['Electrodomésticos','Muebles','Cocina','Baño','Almacenaje','Escritorios','Dormitorio','Salón','Sofás','Sillas','Mesas','Camas y descanso','Armarios y almacenamiento','Mobiliario de exterior','Estanterías','Bancos y taburetes','Muebles de baño','Otros muebles','Muebles auxiliares'];
const app=document.querySelector('#app')!;
app.innerHTML=`<header><a href="#top"><b>QUE CABE AQUÍ</b><small>Encuentra. Compara. Encaja.</small></a><nav><a href="#buscar">Buscar</a><a href="#categorias">Categorías</a><a href="#como">Cómo funciona</a></nav></header><main id="top"><section class="hero"><span>EL BUSCADOR PARA CUANDO EL ESPACIO MANDA</span><h1>Busca productos que <em>sí caben</em> en tu casa.</h1><p>Escribe qué necesitas, añade las medidas del hueco y descubre opciones que encajan.</p><div class="quick" id="buscar"><input id="q" placeholder="Ej. lavavajillas · lavavajillas 45 cm · lavadora · escritorio · mueble TV"><button id="go">Buscar</button></div><div class="hints">${['lavavajillas','lavavajillas 45 cm','lavadora','escritorio','mueble TV'].map(x=>`<button data-q="${x}">${x}</button>`).join('')}</div></section><section class="panel"><h2>¿Qué hueco tienes?</h2><div class="fields"><label>Ancho (cm)<input id="w" type="number"></label><label>Fondo (cm)<input id="d" type="number"></label><label>Alto (cm)<input id="h" type="number"></label><label>Margen de seguridad (cm)<input id="m" type="number" value="0" min="0" step="0.1"></label><label>Categoría<select id="cat"><option value="">Todas</option>${cats.map(x=>`<option>${x}</option>`).join('')}</select></label></div><button class="primary" id="find">Encontrar opciones que encajen →</button><button class="secondary" id="clear">Limpiar</button></section><section class="results"><h2 id="count">Empieza con una búsqueda.</h2><div id="cards"></div></section><section id="categorias"><h2>Categorías</h2><div class="catgrid">${cats.map(x=>`<button data-cat="${x}">${x}</button>`).join('')}</div></section><section id="como" class="how"><h2>Cómo funciona</h2><p>Busca por texto o introduce ancho, fondo y alto. El margen de seguridad se resta de cada medida disponible antes de filtrar.</p></section></main>`;
const norm=(s:string)=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const n=(id:string)=>{const v=(document.querySelector<HTMLInputElement>('#'+id)?.value||'').replace(',','.');return v?Number(v):null};
function aliases(s:string){return s.replace(/\b(lavaplatos|lavavajilla)\b/g,'lavavajillas').replace(/\b(televisor|television|tele)\b/g,'tv');}
function parse(q:string){const s=aliases(norm(q)).replace(/,/g,'.'),pair=s.match(/(\d+(?:\.\d+)?)\s*[x×]\s*(\d+(?:\.\d+)?)/),cm=s.match(/(\d+(?:\.\d+)?)\s*cm/);return {w:pair?+pair[1]:cm&&/(lavavajillas|lavadora|secadora|escritorio|mueble|tv)/.test(s)?+cm[1]:null,d:pair?+pair[2]:null};}
function match(p:Product,q:string){const words=aliases(norm(q)).replace(/\d+(?:[.,]\d+)?/g,' ').split(/[^a-z0-9]+/).filter(x=>x.length>1&&!['cm','de','la','el','los','las','para','con','hasta'].includes(x));const text=norm(p.title+' '+p.category);return words.every(x=>text.includes(x)||(x.endsWith('s')&&text.includes(x.slice(0,-1))));}
function image(p:Product){const list=[p.image,p.fallback,'https://images.weserv.nl/?url='+encodeURIComponent(p.image)].filter(Boolean) as string[];return `<img src="${list[0]}" alt="${p.title}" loading="lazy" data-i="0" onerror="const l=${JSON.stringify(list)};let i=+this.dataset.i+1;if(i<l.length){this.dataset.i=i;this.src=l[i]}else{this.onerror=null;this.replaceWith(Object.assign(document.createElement('div'),{className:'noimg',textContent:'Imagen no disponible'}))}">`;}
function amazon(q:string){const u=new URL('https://www.amazon.es/s');u.searchParams.set('k',q||'productos');u.searchParams.set('tag',TAG);return u.toString();}
function render(){const q=(document.querySelector<HTMLInputElement>('#q')?.value||'').trim(),p=parse(q),w=n('w')??p.w,d=n('d')??p.d,h=n('h'),m=Math.max(0,n('m')??0),cat=(document.querySelector<HTMLSelectElement>('#cat')?.value||'');const uw=w===null?null:w-m,ud=d===null?null:d-m,uh=h===null?null:h-m;const list=products.filter(x=>(!cat||x.category===cat)&&match(x,q)&& (uw===null||x.width<=uw)&&(ud===null||x.depth<=ud)&&(uh===null||x.height<=uh));document.querySelector('#count')!.textContent=list.length?`${list.length} producto${list.length===1?'':'s'} que encaja${list.length===1?'':'n'}`:(q||w||d||h)?'No hay productos exactos en el catálogo':'Empieza con una búsqueda.';document.querySelector('#cards')!.innerHTML=list.length?list.map(x=>`<article><div class="photo">${image(x)}</div><span>${x.category}</span><h3>${x.title}</h3><p>${x.width} × ${x.depth} × ${x.height} cm</p><a href="${x.url}" target="_blank" rel="sponsored noopener noreferrer">Ver producto →</a></article>`).join(''):(q||w||d||h)?`<div class="empty">No hay una ficha exacta todavía. <a href="${amazon(q||'productos')}" target="_blank" rel="sponsored noopener noreferrer">Buscar en Amazon →</a></div>`:'';}
['go','find'].forEach(id=>document.querySelector('#'+id)!.addEventListener('click',render));document.querySelector('#q')!.addEventListener('keydown',e=>{if(e.key==='Enter')render()});document.querySelectorAll<HTMLButtonElement>('[data-q]').forEach(b=>b.onclick=()=>{(document.querySelector('#q') as HTMLInputElement).value=b.dataset.q||'';render()});document.querySelectorAll<HTMLButtonElement>('[data-cat]').forEach(b=>b.onclick=()=>{(document.querySelector('#cat') as HTMLSelectElement).value=b.dataset.cat||'';render()});document.querySelector('#clear')!.addEventListener('click',()=>{['q','w','d','h'].forEach(id=>{const e=document.querySelector<HTMLInputElement>('#'+id);if(e)e.value=''});(document.querySelector('#m') as HTMLInputElement).value='0';(document.querySelector('#cat') as HTMLSelectElement).value='';render()});render();
